# Generated by Django 2.0.2 on 2018-03-09 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choixactif',
            name='logo',
            field=models.ImageField(default='logos/GOOGLE.jpge', upload_to='logos'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='imagefirst',
            field=models.ImageField(default='first/first.png', upload_to='first'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='imagesecond',
            field=models.ImageField(default='second/second.png', upload_to='second'),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='date_debut',
            field=models.DateField(blank=True, help_text='Entrer la date du debut pour la simulation', null=True),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='date_fin',
            field=models.DateField(blank=True, help_text='Entrer la date de la fin pour la simulation', null=True),
        ),
    ]
