# Generated by Django 2.0.2 on 2018-03-10 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0002_auto_20180310_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choixactif',
            name='logo',
            field=models.ImageField(upload_to='logos'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='imagefirst',
            field=models.ImageField(upload_to='first'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='imagesecond',
            field=models.ImageField(upload_to='second'),
        ),
    ]
